# Generated by Django 4.2.7 on 2024-05-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoUpload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoframe',
            name='image',
            field=models.ImageField(upload_to='photo_frame_images'),
        ),
    ]
