# Generated by Django 4.2.7 on 2024-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoUpload', '0003_photoframe_card_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishingcard',
            name='background_image',
            field=models.ImageField(default='default_background.png', upload_to='wishing_card_backgrounds'),
        ),
    ]
