# Generated by Django 4.2.7 on 2024-05-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoUpload', '0004_wishingcard_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishingcard',
            name='message',
        ),
        migrations.AddField(
            model_name='wishingcard',
            name='designation',
            field=models.CharField(default='FDL Family', max_length=100),
        ),
    ]
